---
sudo: false
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.4.4
    env: PUPPET_VERSION="~> 5.0" STRICT_VARIABLES="yes"
  - rvm: 2.5.1
    env: PUPPET_VERSION="~> 6.0" STRICT_VARIABLES="yes"
notifications:
  email: false
